#!/bin/bash

if grep -xqs "VB_ACTIVE=true" /etc/environment
then
    echo -e "\nCannot activate, another virtualbucket is already active.\nRun vb_deactivate to stop the other bucket and run activate again.\n"
else
    sudo sed -i 's/VB_ACTIVE=false/VB_ACTIVE=true/' /etc/environment
    PATH="$PWD/.env/bin:$PATH"
fi
