#!/bin/bash

echo "Setting up"
if ! grep -qs "VB_ACTIVE" /etc/environment
then
    sudo echo -e 'VB_ACTIVE=false' >> /etc/environment
else
    sudo sed -i 's@VB_ACTIVE=.*$@VB_ACTIVE=false@' /etc/environment
    PATH=$(echo $PATH | sed 's@/.*/.env/bin:@@')
fi


