#!/bin/bash

if ! grep -xqs VB_OLD_PATH /etc/environment
then
    mkdir /etc/virtualbucket && cp proto_config /etc/virtualbucket/config && cp proto_activate proto_deactivate /etc/virtualbucket/.
    echo -e 'VB_ACTIVE=false' >> /etc/environment
fi
#cp -n proto_ev.sh /etc/profile.d/vb_ev.sh && /etc/profile.d/vb_ev.sh


