#!/bin/bash

mkdir -p /etc/virtualbucket && cp proto_config /etc/virtualbucket/config && cp proto_activate proto_deactivate /etc/virtualbucket/.

if ! grep -xqs VB_ACTIVE /etc/environment
then
    echo -e 'VB_ACTIVE=false' >> /etc/environment
else
    sed -i 's@VB_ACTIVE=.*$@VB_ACTIVE=false@' /etc/environment
    PATH=$(echo $PATH | sed 's@/.*/.env/bin:@@')
fi


