#!/usr/bin/env bash

# copy vb_* to /usr/bin/. but not right now, not until things are working
mkdir /etc/virtualbucket && cp proto_config /etc/virtualbucket/config && cp proto_activate proto_deactivate /etc/virtualbucket/.
cp -n proto_ev.sh /etc/profile.d/vb_ev.sh && /etc/profile.d/vb_ev.sh


