#!/bin/bash

sudo mkdir -p /etc/virtualbucket && sudo cp proto_config /etc/virtualbucket/config && sudo cp proto_activate proto_deactivate proto_setup proto_remove set_my_bash /etc/virtualbucket/.
sudo cp vb_* /usr/bin/.

if ! grep -qs "VB_ACTIVE" /etc/environment
then
    sudo echo -e 'VB_ACTIVE=false' >> /etc/environment
else
    sudo sed -i 's@VB_ACTIVE=.*$@VB_ACTIVE=false@' /etc/environment
    PATH=$(echo $PATH | sed 's@/.*/.env/bin:@@')
fi


